### ISSUE TITLE
Issue with locate - Sizes of output from _compute do not match 

### ISSUE THREAD

**Issue by TomSHudson** [QuakeMigrate/QuakeMigrate#57] opened 2020-01-30 15:16 UTC
I have detected and triggered events, but for some reason locate is not calculating the coalescence correctly. I've checked the inputs into the line that throws the error, and it is due to the datetime stamp array being 1 item longer than the other outputs. Has anyone seen this before? I don't want to try and fix it if it has already been fixed?

See error message below.

Many thanks,
Tom

Here is the error message:
========================================================================================================================
========================================================================================================================
	QuakeMigrate - Coalescence Scanning - Path: ../outputs/runs - Name: dynamic_trigger_testing
========================================================================================================================
========================================================================================================================

========================================================================================================================
	LOCATE - Determining earthquake location and uncertainty
========================================================================================================================

	Parameters specified:
		Start time                = 2014-06-29T18:00:00.000000Z
		End   time                = 2014-06-29T19:00:00.000000Z
		Number of CPUs            = 12

========================================================================================================================

========================================================================================================================
	EVENT - 802 of 46 - 20140629180029114000
========================================================================================================================

	Determining event location...

	Reading waveform data...
    	Elapsed time: 2.424772 seconds.

	Computing 4D coalescence grid...
Traceback (most recent call last):
  File "/Users/eart0504/opt/anaconda3/envs/Qmigrate_tsh_dev/lib/python3.6/site-packages/pandas/core/internals.py", line 4247, in create_block_manager_from_blocks
    placement=slice(0, len(axes[0])))]
  File "/Users/eart0504/opt/anaconda3/envs/Qmigrate_tsh_dev/lib/python3.6/site-packages/pandas/core/internals.py", line 2685, in make_block
    return klass(values, ndim=ndim, fastpath=fastpath, placement=placement)
  File "/Users/eart0504/opt/anaconda3/envs/Qmigrate_tsh_dev/lib/python3.6/site-packages/pandas/core/internals.py", line 1817, in __init__
    placement=placement, **kwargs)
  File "/Users/eart0504/opt/anaconda3/envs/Qmigrate_tsh_dev/lib/python3.6/site-packages/pandas/core/internals.py", line 109, in __init__
    len(self.mgr_locs)))
ValueError: Wrong number of items passed 1, placement implies 5

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "dynamic_trigger_testing.py", line 218, in <module>
    run_locate(data_in, station_file, lut_out, out_path, run_name, locate_sampling_rate, p_bp_filter, s_bp_filter, p_onset_win, s_onset_win, time_step, locate_decimation, marginal_window=marginal_window, n_cores=n_cores, locate_onset_centred=locate_onset_centred)
  File "dynamic_trigger_testing.py", line 190, in run_locate
    scan.locate(starttime, endtime)
  File "/Users/eart0504/opt/anaconda3/envs/Qmigrate_tsh_dev/lib/python3.6/site-packages/QMigrate-1.0.20.1.16-py3.6.egg/QMigrate/signal/scan.py", line 622, in locate
    self._locate_events(start_time, end_time)
  File "/Users/eart0504/opt/anaconda3/envs/Qmigrate_tsh_dev/lib/python3.6/site-packages/QMigrate-1.0.20.1.16-py3.6.egg/QMigrate/signal/scan.py", line 884, in _locate_events
    columns=["DT", "COA", "X", "Y", "Z"])
  File "/Users/eart0504/opt/anaconda3/envs/Qmigrate_tsh_dev/lib/python3.6/site-packages/pandas/core/frame.py", line 297, in __init__
    copy=copy)
  File "/Users/eart0504/opt/anaconda3/envs/Qmigrate_tsh_dev/lib/python3.6/site-packages/pandas/core/frame.py", line 474, in _init_ndarray
    return create_block_manager_from_blocks([values], [columns, index])
  File "/Users/eart0504/opt/anaconda3/envs/Qmigrate_tsh_dev/lib/python3.6/site-packages/pandas/core/internals.py", line 4256, in create_block_manager_from_blocks
    construction_error(tot_items, blocks[0].shape[1:], axes, e)
  File "/Users/eart0504/opt/anaconda3/envs/Qmigrate_tsh_dev/lib/python3.6/site-packages/pandas/core/internals.py", line 4233, in construction_error
    passed, implied))
ValueError: Shape of passed values is (1, 5), indices imply (5, 5)

**Comment by TomSHudson** [comment] 2020-01-30 15:17
(This is occurring on master branch)

**Comment by hemmelig** [comment] 2020-05-05 20:00
I think I have managed, by chance, to identify the root cause of the issue. It relates to the following code block:

```
daten, max_coa, max_coa_norm, loc, map_4d = self._compute(w_beg, w_end,
                                                          self.data.signal,
                                                          self.data.availability)
coord = self.lut.xyz2coord(np.array(loc).astype(int))
event_coa_data = pd.DataFrame(np.array((daten,
                                        max_coa,
                                        coord[:, 0],
                                        coord[:, 1],
                                        coord[:, 2])).transpose(),
                              columns=["DT", "COA", "X", "Y", "Z"])
```

If one of the `numpy.ndarray`s (daten, max_coa, coord[:, 1] etc) does not have the same length, it will chuck this ValueError, as the .tranpose() method will not work as expected.

```
> import numpy as np
> import pandas as pd
> a = np.array([1,2,3])
> b = a.copy()
> c = a.copy()
> df = pd.DataFrame(np.array((a, b, c)).transpose(), columns=["A", "B", "C"])
> print(df)
   A  B  C
0  1  1  1
1  2  2  2
2  3  3  3
> a = np.array([1, 2])
> df = pd.DataFrame(np.array((a, b, c)).transpose(), columns=["A", "B", "C"])
ValueError: Shape of passed values is (3, 1), indices imply (3, 3)
```

This has been addressed in the upcoming version in two ways:
1. The generation of timestamps is now done through the Event.mw_times() method, which utilises the ObsPy Traces.times() method. We encountered another issue where simply making a numpy array with (starttime, endtime + sample_size, sample_size) generated too many samples (perhaps an ObsPy UTCDateTime thing?)

2. Changed how the values are assigned to a DataFrame - now use a dictionary.
```
coa_data = pd.DataFrame({"DT": times,
                         "COA": max_coa,
                         "COA_NORM": max_coa_n,
                         "X": coord[:, 0],
                         "Y": coord[:, 1],
                         "Z": coord[:, 2]})
```

**Closed by hemmelig** 2020-05-05 20:00 UTC
Labels: bug
